import { z } from "zod";
import type { DayDigest, Entry } from "../types.js";
import { agentMetadata } from "@claude-lens/parser";

/** Built once at module load from the registry. New agents auto-appear
 *  here when added to packages/parser/src/agent-metadata.ts; no prompt
 *  edit required. */
const AGENT_NAMING_TABLE = agentMetadata
  .map((m) => `  - agent="${m.kind}" → render as "${m.displayName}"`)
  .join("\n");

const SuggestionSchema = z.object({
  headline: z.string().min(1).max(80),
  body: z.string().min(1).max(300),
});

export const DayDigestResponseSchema = z.object({
  headline: z.string().min(1).max(160),
  narrative: z.string().max(1200).nullable(),
  what_went_well: z.string().max(400).nullable(),
  what_hit_friction: z.string().max(400).nullable(),
  suggestion: SuggestionSchema.nullable(),
  /** ≤ 120 chars, quotable by the week digest. Null on trivial days where
   *  day_signals.dominant_shape is null. Optional for backward compat with
   *  pre-refactor cached responses. */
  day_signature: z.string().max(160).nullable().optional(),
}).passthrough();

export type DayDigestResponse = z.infer<typeof DayDigestResponseSchema>;

const SYSTEM_PROMPT = `You are synthesizing a developer's coding-agent activity for a single local day into a short, honest narrative digest.

The user runs MULTIPLE coding agents (Claude Code, OpenAI Codex CLI, possibly more). The day's input may include sessions from any registered agent — they all merge into one fleet view. When the day spans more than one agent (see DAY FACTS.agent_breakdown and per_entry.agent), the narrative SHOULD name the agents explicitly so the reader sees how the fleet was used.

Input is:
- DAY FACTS: deterministic aggregates (agent_min, agent_breakdown, projects, shipped PRs, concurrency_peak, top_flags, top_goal_categories)
- DAY SIGNALS: a deterministic classification of HOW the user worked today — dominant_shape (named orchestration pattern, e.g. spec-review-loop, chunk-implementation, solo-build, "mixed", or null on a trivial day), shape_distribution (per-shape session counts), skills_loaded (with stock vs user-authored origin), user_authored_skills_used, user_authored_subagents_used (with sample evidence), prompt_frames (Claude features the user employs vs personal habits), comm_style (verbosity histogram, external_refs, steering counts), brainstorm_warmup_session_count, todo_ops_total, plan_mode_used. Treat day_signals as the analytical foundation — your narrative anchors here.
- ENTRY SUMMARIES: up to 12 per-session brief_summaries already generated by the enrichment pass
- FRICTION LINES: up to 6 entry-level friction_detail sentences (where present)
- USER INSTRUCTIONS: up to 10 load-bearing asks the user gave across the day

Output ONE JSON object with six fields:

1. headline (string, one sentence, <= 120 chars):
   Second-person. Concrete verb + concrete noun. Lead with the most characteristic work of the day.
   Good: "You shipped the Team Edition timeline after two subagent retries."
   Bad:  "You had a productive day."

2. narrative (string, 2-4 sentences, <= 600 chars, or null):
   Second-person. Weave the top 3-5 entries into a coherent arc. Name projects. Name specific wins or blockers. Do NOT list every entry.

3. what_went_well (string, ONE sentence or null):
   The strongest positive signal from the day. Tie to a concrete cause ("Subagent loop settled after you split the spec review"). Null if the day was truly friction-dominated.

4. what_hit_friction (string, ONE sentence or null):
   The most load-bearing friction. Tie to a concrete cause. Null if the day was smooth.

5. suggestion (object { headline: string <= 60 chars, body: string <= 240 chars } or null):
   One actionable next step for tomorrow, grounded in today's pattern. Null if nothing obvious suggests itself; don't pad with truisms.

6. day_signature (string <= 120 chars, or null):
   ONE sentence characterizing today's shape that the week digest can quote verbatim.
   Format: "<shape> on <project>: <key signal>, <outcome>".
   Examples:
     - "spec-review-loop on Phase 1b: 3 reviewers + 1 implementer, shipped clean"
     - "solo-build with mid-run redirect: ConnectionRefused at minute 70"
     - "research-then-build: 3 Explore subagents, ahora v8 spec drafted"
     - "mixed: 2 spec-review-loop + 1 chunk-implementation, all shipped"
   Set to null ONLY when day_signals.dominant_shape is null (trivial day with no characterizable work).

CRITICAL RULES:

- Second-person ("you ..."), not third-person.
- Copy the user's phrasings where useful; do not invent features or outcomes not in the input.
- **When DAY FACTS.agent_breakdown has more than one agent, the narrative MUST name them.** Render each agent kind with its canonical display name:
${AGENT_NAMING_TABLE}
Treat the per-agent split as a load-bearing signal — if the user delegated specific work to a non-default agent, that distinction belongs in headline / narrative / what_went_well / what_hit_friction.
- Do not mention a project unless it's in DAY FACTS.projects AND that project has a non-trivial entry (outcome != "trivial") in per_entry.
- **Attribute every PR to its correct project using the per_entry list** — never join a PR title with a project from a different entry. If a project only has a trivial/warmup entry, do NOT describe any deliverable as happening in it.
- Do not fabricate PR counts, commits, or timestamps.
- If input is sparse (<= 2 entries or <= 10 active_min), err shorter — a one-line headline + null narrative is fine.
- **A day where only trivial/warmup entries exist has no "shipped" work** — say so plainly; do not imply deliverables that didn't happen.

ANCHORING (every what_went_well / what_hit_friction / suggestion claim must cite something concrete):
  Every cited reason MUST tie back to one of:
    - day_signals.dominant_shape value (e.g. "spec-review-loop"), OR
    - "day_signals.<key>" where key is one of: shape_distribution, comm_style, user_authored_skills_used, user_authored_subagents_used, prompt_frames, plan_mode_used, brainstorm_warmup_session_count
  When the day has only one session, anchor to that session's entry.signals.working_shape value if available.
  This keeps the prose grounded in the day's actual pattern rather than floating prose.

RESPOND WITH ONLY VALID JSON (no prose, no code fence):

{
  "headline": "...",
  "narrative": "..." | null,
  "what_went_well": "..." | null,
  "what_hit_friction": "..." | null,
  "suggestion": { "headline": "...", "body": "..." } | null,
  "day_signature": "..." | null
}`;

export const DIGEST_DAY_SYSTEM_PROMPT = SYSTEM_PROMPT;

function trunc(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1) + "…";
}

function prettyProject(p: string): string {
  const parts = p.split("/").filter(Boolean);
  return parts[parts.length - 1] ?? p;
}

export function buildDigestUserPrompt(base: DayDigest, entries: Entry[]): string {
  const enriched = entries.filter(e => e.enrichment.status === "done");

  const summaries = enriched
    .slice(0, 12)
    .map(e => `- (${prettyProject(e.project)}, ${Math.round(e.numbers.active_min)}m) ${trunc(e.enrichment.brief_summary ?? "", 240)}`)
    .join("\n");

  const frictions = enriched
    .map(e => e.enrichment.friction_detail)
    .filter((x): x is string => !!x)
    .slice(0, 6)
    .map((f, i) => `${i + 1}. ${trunc(f, 240)}`)
    .join("\n");

  const instructions = enriched
    .flatMap(e => e.enrichment.user_instructions)
    .slice(0, 10)
    .map((s, i) => `${i + 1}. ${trunc(s, 240)}`)
    .join("\n");

  // Build per-entry facet so LLM can correlate: agent (for cross-tool
  // narratives), project, active_min, outcome, pr_titles, flags,
  // brief_summary. Prevents mis-attribution of PRs to worktrees where
  // no work actually happened (e.g., trivial warmup entries).
  const per_entry = entries.map(e => ({
    agent: e.agent ?? "claude-code",
    project: prettyProject(e.project),
    active_min: Math.round(e.numbers.active_min * 10) / 10,
    outcome: e.enrichment.outcome ?? "pending",
    pr_titles: e.pr_titles,
    flags: e.flags,
    primary_model: e.primary_model,
    brief_summary: e.enrichment.status === "done" ? e.enrichment.brief_summary : null,
    friction_detail: e.enrichment.status === "done" ? e.enrichment.friction_detail : null,
  }));

  // Per-agent rollup so the LLM can call out fleet shape directly. When
  // the day has only one agent this is uninteresting; when it spans
  // multiple agents it should surface in the narrative.
  const agentBreakdown = (() => {
    const counts = new Map<string, { sessions: number; active_min: number; tools_total: number }>();
    for (const e of entries) {
      const k = e.agent ?? "claude-code";
      const c = counts.get(k) ?? { sessions: 0, active_min: 0, tools_total: 0 };
      c.sessions += 1;
      c.active_min += e.numbers.active_min;
      c.tools_total += e.numbers.tools_total;
      counts.set(k, c);
    }
    return Array.from(counts.entries()).map(([agent, v]) => ({
      agent,
      sessions: v.sessions,
      active_min: Math.round(v.active_min * 10) / 10,
      tools_total: v.tools_total,
    }));
  })();

  const facts = {
    date: base.key,
    agent_min: base.agent_min,
    agent_breakdown: agentBreakdown,
    project_count: base.projects.length,
    projects: base.projects.map(p => ({
      name: p.display_name, share_pct: p.share_pct, entry_count: p.entry_count,
    })),
    shipped: base.shipped.map(s => ({ title: s.title, project: s.project })),
    concurrency_peak: base.concurrency_peak,
    top_flags: base.top_flags,
    top_goal_categories: base.top_goal_categories,
    per_entry,
  };

  const daySignalsBlock = base.day_signals
    ? `\n\nDAY SIGNALS:\n${JSON.stringify(base.day_signals, null, 2)}`
    : "";

  return `DAY FACTS:
${JSON.stringify(facts, null, 2)}${daySignalsBlock}

ENTRY SUMMARIES (up to 12, most significant first):
${summaries || "(none — no enriched entries)"}

FRICTION LINES (up to 6):
${frictions || "(none — smooth day)"}

USER INSTRUCTIONS (up to 10 load-bearing asks):
${instructions || "(none)"}`;
}
