import {
  readDayDigest, writeWeekDigest,
  readWeekDigest,
  getCurrentWeekDigestFromCache, setCurrentWeekDigestInCache,
} from "./digest-fs.js";
import { listEntriesForDay } from "./fs.js";
import { runDayDigestPipeline, type PipelineEvent, type PipelineOptions as DayPipelineOptions } from "./digest-day-pipeline.js";
import { generateWeekDigest, buildDeterministicWeekDigest, weekDates } from "./digest-week.js";
import { pickTopSessions, buildSessionSlice, generateTopSession, type RawSessionEvent } from "./top-sessions.js";
import { getAnySession } from "@claude-lens/parser/fs";
import { appendSpend } from "./budget.js";
import { computeCostUsd } from "./enrich.js";
import { writeInteractiveLock, removeInteractiveLock } from "./pipeline-lock.js";
import type { CallLLM } from "./enrich.js";
import type { AiFeaturesSettings } from "./settings.js";
import type { DayDigest, Entry, WeekDigest, WeekTopSession } from "./types.js";

export type WeekPipelineOptions = {
  settings: AiFeaturesSettings;
  force?: boolean;
  callLLM?: CallLLM;
  now?: () => number;
  /** Current local Monday in server TZ; if `monday === currentWeekMonday`, persist to in-memory cache instead of disk. */
  currentWeekMonday: string;
  /** Current local day; sub-pipelines need this. */
  todayLocalDay: string;
  caller?: "web" | "cli" | "daemon";
};

/** Returns the Monday (in local TZ) for the given local YYYY-MM-DD. */
export function mondayFor(localDay: string): string {
  const d = new Date(`${localDay}T00:00:00`);
  const dow = d.getDay(); // 0=Sun, 1=Mon, ...
  const offset = dow === 0 ? -6 : 1 - dow;
  d.setDate(d.getDate() + offset);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export async function* runWeekDigestPipeline(
  monday: string,
  opts: WeekPipelineOptions,
): AsyncGenerator<PipelineEvent, void, void> {
  const now = opts.now ?? (() => Date.now());
  const isCurrentWeek = monday === opts.currentWeekMonday;
  const aiOn = opts.settings.enabled;

  // Short-circuit: past week, cached on disk, !force
  if (!isCurrentWeek && !opts.force) {
    const cached = readWeekDigest(monday);
    if (cached) { yield { type: "digest", digest: cached }; return; }
  }

  // Short-circuit: current week, cached in TTL, !force
  if (isCurrentWeek && !opts.force) {
    const cached = getCurrentWeekDigestFromCache(monday, now());
    if (cached) { yield { type: "digest", digest: cached }; return; }
  }

  // Stage 0: collect day digests for the 7 dates of the week.
  // Past-day digests get auto-generated inline if missing. Today's digest
  // is read from cache only — never force-generated by a week-pipeline trigger.
  yield { type: "status", phase: "load_dependencies", text: `Loading 7 days for week of ${monday}` };
  const dates = weekDates(monday);
  const dayDigests: DayDigest[] = [];

  for (const date of dates) {
    const isFuture = date > opts.todayLocalDay;
    if (isFuture) {
      yield { type: "dependency", kind: "day", key: date, status: "cached" };
      continue;
    }
    const isToday = date === opts.todayLocalDay;

    const cached = isToday ? null : readDayDigest(date);
    if (cached) {
      dayDigests.push(cached);
      yield { type: "dependency", kind: "day", key: date, status: "cached" };
      continue;
    }

    if (isToday) {
      // Read today via the day pipeline (TTL-cached short-circuit). Cascade
      // force=true through so a forced week regen also forces today's
      // enrichment; otherwise the day comes back deterministic-only and the
      // week narrative falls back to the empty-headline path.
      const subOpts: DayPipelineOptions = {
        settings: opts.settings, force: opts.force ?? false, callLLM: opts.callLLM, now: opts.now,
        todayLocalDay: opts.todayLocalDay, caller: opts.caller,
      };
      let captured: DayDigest | null = null;
      let failed = false;
      for await (const ev of runDayDigestPipeline(date, subOpts)) {
        if (ev.type === "digest" && ev.digest.scope === "day") captured = ev.digest as DayDigest;
        if (ev.type === "error") { failed = true; break; }
      }
      if (captured) {
        dayDigests.push(captured);
        yield { type: "dependency", kind: "day", key: date, status: "cached" };
      } else if (failed) {
        yield { type: "dependency", kind: "day", key: date, status: "failed" };
      }
      continue;
    }

    // Past day, no cache → generate inline via the day pipeline.
    const subOpts: DayPipelineOptions = {
      settings: opts.settings, force: false, callLLM: opts.callLLM, now: opts.now,
      todayLocalDay: opts.todayLocalDay, caller: opts.caller,
    };
    let captured: DayDigest | null = null;
    let failed = false;
    for await (const ev of runDayDigestPipeline(date, subOpts)) {
      // Forward the sub-pipeline's entry/progress events so the SSE client
      // sees enrichment ticking, but suppress sub-digest "digest" events
      // (we'll emit our own week digest at the end). Suppress "saved" too —
      // the user is generating a week, not a day.
      if (ev.type === "digest") {
        if (ev.digest.scope === "day") captured = ev.digest as DayDigest;
        continue;
      }
      if (ev.type === "saved") continue;
      if (ev.type === "error") { failed = true; continue; }
      yield ev;
    }
    if (captured) {
      dayDigests.push(captured);
      yield { type: "dependency", kind: "day", key: date, status: "generated" };
    } else if (failed) {
      yield { type: "dependency", kind: "day", key: date, status: "failed" };
    }
  }

  if (dayDigests.length === 0) {
    yield { type: "error", message: `no day digests available for week of ${monday}` };
    return;
  }

  // Load entries indexed by local_day. Used for longest_run / hours_distribution /
  // interaction_modes / threads, plus on-the-fly DaySignals fallback for cached
  // pre-refactor day digests that lack day_signals.
  const entriesByDay = new Map<string, Entry[]>();
  for (const date of dates) {
    if (date > opts.todayLocalDay) continue;
    entriesByDay.set(date, listEntriesForDay(date) as Entry[]);
  }

  if (aiOn) writeInteractiveLock();
  try {
    let digest: WeekDigest;

    // ── Top-session prep (deterministic — runs even without AI on) ─────
    // We pick + load slices upfront so when AI is on we can fire the
    // per-session LLM calls in parallel WITH the week-narrative call,
    // not sequentially after it. Picks are independent of the week
    // synth result.
    const dayDigestByDate = new Map(dayDigests.map(dd => [dd.key, dd]));
    const picks = aiOn ? pickTopSessions(entriesByDay) : [];
    const topSlicesPrep = await Promise.all(picks.map(async (entry) => {
      try {
        // getAnySession dispatches across the AgentSource registry so a
        // Codex pick resolves to its rollout, not just Claude transcripts.
        const sessionDetail = await getAnySession(entry.session_id);
        if (!sessionDetail) return null;
        const events = sessionDetail.events as unknown as RawSessionEvent[];
        const dd = dayDigestByDate.get(entry.local_day);
        return {
          entry,
          slice: buildSessionSlice(entry, events, dd?.day_signature ?? null),
        };
      } catch (err) {
        console.warn(`[top-session] slice prep failed for ${entry.session_id}: ${(err as Error).message}`);
        return null;
      }
    }));
    const topSlices = topSlicesPrep.filter((x): x is NonNullable<typeof x> => x !== null);

    if (aiOn) {
      // Parallel mode: fire the week narrative + all top-session deep-dives
      // concurrently. The week LLM and top-session LLMs have no input
      // dependency on each other, so wall-clock = max(week, max(top_sessions))
      // instead of the sum. With --effort medium and the MCP fix in place,
      // contention on the shared 5-hour subscription budget is much lower
      // than what we observed pre-fix.
      yield {
        type: "status", phase: "synth",
        text: topSlices.length > 0
          ? `Synthesizing week narrative + diving into ${topSlices.length} top session${topSlices.length === 1 ? "" : "s"} in parallel`
          : "Synthesizing week narrative",
      };
      const progressQueue: Array<{ bytes: number; elapsed_ms: number }> = [];
      const weekPromise = generateWeekDigest(monday, dayDigests, {
        model: opts.settings.model, callLLM: opts.callLLM,
        entriesByDay,
        // The current week often has only Monday's data when freshly forced —
        // unblock the LLM synth in that case so the user gets a usable
        // narrative on day one of the week.
        allowSingleDay: opts.force === true && isCurrentWeek,
        onProgress: info => { progressQueue.push({ bytes: info.bytes, elapsed_ms: info.elapsedMs }); },
      });
      const topSessionsPromise = Promise.all(topSlices.map(({ entry, slice }) =>
        generateTopSession(slice, {
          model: opts.settings.model, callLLM: opts.callLLM,
        }).then(r => ({ entry, ...r })).catch(err => {
          console.warn(`[top-session] LLM failed for ${entry.session_id}: ${(err as Error).message}`);
          return null;
        }),
      ));

      let weekDone = false, topDone = false;
      weekPromise.finally(() => { weekDone = true; });
      topSessionsPromise.finally(() => { topDone = true; });
      while (!weekDone || !topDone) {
        await new Promise(r => setTimeout(r, 500));
        if (progressQueue.length > 0) {
          const latest = progressQueue[progressQueue.length - 1]!;
          yield { type: "progress", phase: "synth", bytes: latest.bytes, elapsed_ms: latest.elapsed_ms };
          progressQueue.length = 0;
        }
      }
      const weekR = await weekPromise;
      const topResults = await topSessionsPromise;
      digest = weekR.digest;
      if (weekR.usage) {
        appendSpend({
          ts: new Date().toISOString(), caller: opts.caller ?? "web",
          model: digest.model ?? opts.settings.model,
          input_tokens: weekR.usage.input_tokens,
          output_tokens: weekR.usage.output_tokens,
          cost_usd: digest.cost_usd ?? 0,
          kind: "week_digest", ref: monday,
        });
      }
      // Persist top sessions onto the digest in pick order, attribute spend.
      const topSessions: WeekTopSession[] = [];
      for (const r of topResults) {
        if (!r) continue;
        // Stamp the source agent on the top session so the renderer can
        // show an agent badge for non-Claude picks.
        topSessions.push({ ...r.topSession, agent: r.entry.agent });
        if (r.usage) {
          appendSpend({
            ts: new Date().toISOString(), caller: opts.caller ?? "web",
            model: opts.settings.model,
            input_tokens: r.usage.input_tokens,
            output_tokens: r.usage.output_tokens,
            cost_usd: computeCostUsd(opts.settings.model, r.usage.input_tokens, r.usage.output_tokens),
            kind: "top_session", ref: `${monday}/${r.entry.session_id}`,
          });
        }
      }
      // Only attach top_sessions when the week LLM succeeded — otherwise the
      // cards would float without the surrounding narrative scaffolding.
      if (digest.headline && topSessions.length > 0) {
        digest.top_sessions = topSessions;
      }
    } else {
      digest = buildDeterministicWeekDigest(monday, dayDigests, { entriesByDay });
    }

    if (!isCurrentWeek) {
      writeWeekDigest(digest);
      yield { type: "saved", path: `~/.cclens/digests/week/${monday}.json` };
    } else {
      digest.is_live = true;
      setCurrentWeekDigestInCache(monday, digest, now());
      // Force=true on the current week is an explicit user-driven generation.
      // The default rule keeps current-week digests in-memory only (so they
      // recompute as the week progresses), but Next.js bundles each route
      // with its own module scope — the API route's in-memory cache isn't
      // visible to the insights page's RSC. Writing to disk on force=true
      // bridges that gap so the user actually sees the digest they paid to
      // generate. The deterministic-data view stays correct because every
      // future page load will refresh from this snapshot until either the
      // user re-forces or the next day's data triggers a fresh write.
      if (opts.force === true) {
        writeWeekDigest(digest);
        yield { type: "saved", path: `~/.cclens/digests/week/${monday}.json` };
      }
    }

    yield { type: "digest", digest };
  } finally {
    if (aiOn) removeInteractiveLock();
  }
}
